# New ports collection makefile for:    assl
# Date created:         March 5, 2012
# Whom:                 Dale Rahn <drahn@conformal.com>
#
# $FreeBSD$
# 

PORTNAME=       assl
PORTVERSION=    0.12.2
CATEGORIES=     security
MASTER_SITES=   https://opensource.conformal.com/snapshots/assl/ \
                LOCAL/bf

MAINTAINER=     None
COMMENT=        hide awful SSL API in a sane interface

LICENSE=        ISCL
LICENSE_COMB=   single

BUILD_DEPENDS=  ${LOCALBASE}/lib/libclens.a:${PORTSDIR}/devel/clens
LIB_DEPENDS=

.include <bsd.port.mk>
