.include "${.CURDIR}/shlib_version"
SHLIB_MAJOR=${major}

MANDIR=$(LOCALBASE)/man/man

CFLAGS+= -fdiagnostics-show-option
CFLAGS+= -DNEED_LIBCLENS
CFLAGS+= -I${INCDIR}/clens -I${LOCALBASE}/ssl/include
